version: '3.9'

services:
  bot:
    image: "ithelpbot"
    container_name: "ithelpbot_prod"
    restart: always
    command: python app.py
    env_file:
      - ".env.prod"
    volumes:
#      - type: bind
#        source: /home/gulyaeve/Документы/ithelpbot_data/json
#        target: /home/json
      - type: bind
        source: /home/gulyaeve/Документы/ithelpbot_data/logs
        target: /home/logs