version: '3.1'

services:
  db:
    container_name: "database"
    image: "sameersbn/postgresql"
    env_file:
     - ".env.dev"
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./postgres:/var/lib/postgresql
  bot:
    container_name: "ithelpbot_dev"
    build:
      context: .
    links:
      - "db:database"
    restart: always
    env_file:
      - ".env.dev"
    command: python app.py
    volumes:
      - .:/src
    depends_on:
      - db